[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'cd application && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn application.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
